# A. Site Settings
locale          :      # Fallback "en-US"
title           :  Chulapa # Fallback "repository_name" REV
title_separator :      # Fallback " | "
subtitle        :  A Jekyll theme for Github Pages powered by Bootstrap 


url             : 
baseurl         : 

algolia:                                                                
  application_id: KOIKA5PDQO
  index_name: chulapa

# Site Author
author:
  name    : DHH
  avatar  : 

# Social Sharing
twitter:
  site               :   #Avoid the @
og_image             : "./assets/img/gallery/david-monje-YwrD58FfX9g-unsplash.jpg"

# Disqus ID

disqus_shortname: chulapa #Your site id : check your address https://{{ disqus.shortname }}.disqus.com/admin/

# Web tracking using Google
gtag_id:    # gtag.js configuration Google Tag ID 
analytics_id:  # analytics.js id. Provided for backward compatibility, better use gtag_id
# B. Navigations

navbar:
  brand:
    title: Home
    url: 
    img: https://i1.wp.com/www.gritosdemadrid.es/wp-content/uploads/2018/05/15x15-Puerta-del-Sol-Cartel-Calle-Azulejo.jpg
  nav:
  - title: Showcase
    url: /bootstrap
  - title: Second Level
    child:
    - title: Liquid examples
      url:  /liquid
    - title: Demos
      url: /demo
  - title: Another
    child:
    - title: New
      url: /new
    - title: External url
      url: https://www.google.com/
  - title: Github
    url: https://github.com/dieghernan

footer:
  links:
    - label: "RSS"
      icon: "fa-rss"
      url:  https://www.example.com
    - label: "Twitter"
      icon: "fa-twitter"
      # url:
    - label: "Facebook"
      icon: "fa-facebook"
    - label: "GitHub"
      icon: "fa-github"
      # url:
    - label: "Instagram"
      icon: "fa-instagram"
  

# C. Theme Settings
# Code highlighter 
highlight-skin  :      # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options

# Google Fonts https://fonts.google.com/, add as many as you want
googlefonts:
  - url : 'https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap'

  

# Theme and colors
chulapa-skin: 
  highlight   :  # Fallback "default" #See http://jwarby.github.io/jekyll-pygments-themes for options
  theme       : deeply # Optional predefined skins
  autothemer  :   # Bool: Use autotheming
  vars        :    
    chulapa-col: # Fallback "crimson"
    font-family-sans-serif: #Roboto, sans-serif
    hero-chulapa-bg-color: 
    
#D. Defaults and collections

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type: "base"
  -
    scope:
      path: ""
      type: "demo"
    values:
      layout: "default"
      header_type: "hero"
      show_bottomnavs: true
      show_sociallinks: true


#Collections
collections:
  demo:
    output: true



# XX. Other settings - no need to modify
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor

include:
 - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


github: [metadata]
