# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Based on https://github.com/actions/starter-workflows/blob/main/pages/jekyll.yml
name: Push pages to branch

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master","main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "10 8 * * 1,3,5"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to work out-of-the-box with jekyll-github-metadata
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        # https://github.com/ruby/setup-ruby/releases/tag/v1.207.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 2 # Increment this number if you need to re-download cached gems
          working-directory: 'docs' # Default directory of the site, change it to 'docs' if the site is hosted in (e.g.) 'docs' folder
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: |
          cd  docs # Change it to 'docs' if the site is hosted in (e.g.) 'docs' folder 
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        shell: bash
        env:
          JEKYLL_ENV: production
      - name: Deploy ðŸš€
        # Deploy to branch
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: docs/_site/ # Change it to 'docs/_site/' if the site is hosted in (e.g.) 'docs' folder
